### ISSUE TITLE
Pubs/Mgt error with Tidal, Collision, Fish

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#106]
From Grace:

> I just came across this error. I had entered Tidal, Collision, Fish as tags. The error only occurs on the Management and Publications pages. All other pages look fine. Looks like an issue with the Tethys API?
>
> ![image](https://user-images.githubusercontent.com/2837257/149846051-b521d5cd-0620-47d0-b797-22526778c87a.png)

**Comment by bbest** [comment]
When running Shiny app from rstudio.marineenergy.app:

```
Warning: Error in : Mapped vectors must have consistent lengths:
* `.x` has length 3
* `.y` has length 2
  119: map2_chr
  118: .f [/share/github/apps_dev/scripts/shiny_report.R#375]
  117: map
```

**Comment by bbest** [comment]
This is complicated by the lack of **Consequences** tags in Publications which gets handled separately.

**Comment by cdobbelaere** [comment]
@bbest, It looks like the issue in displaying management/publications (as documented [above](https://github.com/marineenergy/apps/issues/106#issuecomment-1014951246)) may be due to `get_content_tag_categories("publications")` returning `character(0)`: 
<img width="694" alt="Screen Shot 2022-01-18 at 11 03 00 AM" src="https://user-images.githubusercontent.com/69017359/150002187-aa07b1b3-9972-4918-97c9-57df2d7f488d.png">

**Comment by bbest** [comment]
fixed with https://github.com/marineenergy/apps/commit/d7cdcdf07c39a5c04983e25f5155df7cbcbf530f
