### ISSUE TITLE
project update - remove unused functions and associated draft files?

### ISSUE THREAD

**Issue by Neil-Swanson** [marineenergy/apps#128]
Updated projects Google sheet and re-ran update functions in ~share/github/apps_dev/scripts/update_all.R. Only 'update_projects()' function runs and is present in the ~share/github/apps_dev/scripts/update.R'. The following functions do not exist; can the calls be deleted in update_all.R?

update_project_sites()
update_project_timelines()

**Comment by bbest** [comment]
Note: had to add extra symbol of `'triangle-down'` to match with newly added permit_type `"Decommissioning"` here:

https://github.com/marineenergy/apps/commit/cab065349f9aa6fd13f9288f08ffb8861865c44d#diff-3490322c3f0ea3493b574aca72b1352d290c3f624b00ef631fcaaf3e32c5ec0fR903-R904

because of extra check in line that follows:

  ```r
  stopifnot(length(permit_types) == length(symbls_type))
  ```

per new permit_type `"Decommissioning"` in `data/project_permit_types.csv`:

  - https://github.com/marineenergy/apps/commit/b983ef9af97f07773ad4562a97326c27342b28a2#diff-4987a66a628298cd491165e38aaa6392175393e277b9945771c882c6ce4fa22bR14
