### ISSUE TITLE
Spatial query funky for cetacean-bia

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#20]
Hey @geocoug,

Something seems amiss with our spatial query for cetacean-bia in [spatial | marineenergy.app - Google Sheets](https://docs.google.com/spreadsheets/d/1MMVqPr39R5gAyZdY2iJIkkIdYqgEBJYQeGqDk1z-RKQ/edit#gid=936111013) or in the R code (see marineenergy/api#3, marineenergy/api#4). I'm getting all kinds of locations outside the targeted area when querying, eg the Gulf of Maine:

![image](https://user-images.githubusercontent.com/2837257/112157002-046bc080-8ba4-11eb-8921-8bec5b150f51.png)

### 3.3 Marine Mammals: Biologically Important Areas for Cetaceans

* Alaskan Beaufort Sea
* Gulf of Alaska
* Hawaii Island
* ...

![image](https://user-images.githubusercontent.com/2837257/112157457-76440a00-8ba4-11eb-9615-ff4f3dd49f6f.png)

**Comment by geocoug** [comment]
The AOI passed into the PostGIS `ST_BUFFER()` needs to be cast as geography instead of geometry in [functions.R](https://github.com/marineenergy/apps/blob/892b92ce714d492c5926a449ad8d0a66296000c8/functions.R#L223).

Current buffer syntax, which is capturing the entire planet, and therefore all available data in a dataset: `select ST_BUFFER({aoi_sql}, {ds$buffer_nm} * 1852) as geom ),`

**Fix**: `select ST_BUFFER(({aoi_sql})::geography, {ds$buffer_nm} * 1852) as geom ),`

This shorthand type cast requires that only 1 row to be returned in `aoi_sql`. When the user draws multiple polygons, we use `ST_COLLECT()` which _dissolves_ polygons into a single feature (versus a `UNION` which would return a row per polygon).

@bbest - Also noticing we didn't add the nautical mile conversion for all of our buffer distances.

**Comment by bbest** [comment]
Awesome find @geocoug 🥳  Shall I implement the fixes or are you okay proceeding?
